name: Warehouse build
on:
  push:
    branches:
      - 'master'
jobs:
  warehouse:
    name: Publish image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./warehouse_service
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        # Build JAR file
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew 
      - name: Build JAR file
        run: ./gradlew bootJar
        # Publish image to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          #context: ./warehouse_service
          file: ./warehouse_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/warehouse:latest
